### ISSUE TITLE
Can't pod install

### ISSUE THREAD

**Issue by vBoykoGit** [ferhatabd/FAStoryKit#1]
```
FAStoryKitStarter-master % pod install
Analyzing dependencies
[!] No podspec found for `FAGlobalKit` in `/Users/abdullahoglu/Desktop/Projects/Frameworks/FAGlobalKit`
```
Where can i find this frameworks?
pod 'FAGlobalKit', :path => '/Users/abdullahoglu/Desktop/Projects/Frameworks/FAGlobalKit'
pod 'SessionKit', :path => '/Users/abdullahoglu/Desktop/Projects/Frameworks/SessionKit'

**Comment by stas-litvinov** [comment]
Right, the project does not build because of that..
Here they are:
[FAGlobalKit](https://github.com/ferhatabd/FAGlobalKit)
[SeesionKit](https://github.com/ferhatabd/SessionKit)

**Comment by fukemy** [comment]
hi, i modified pod but still not working
```
target 'FAStoryKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FAStoryKit

  pod 'FAGlobalKit', :path => 'https://github.com/ferhatabd/FAGlobalKit'
  pod 'SessionKit', :path => 'https://github.com/ferhatabd/SessionKit'
end
```

i got this error : 
[!] No podspec found for `FAGlobalKit` in `https://github.com/ferhatabd/FAGlobalKit`

**Comment by ferhatabd** [comment]
Hi @fukemy, there is a dependency to a private repo. I'll do some changes so that it's not required anymore. 
I'll try to have a look into this today or tomorrow and let you know ✌🏻

**Comment by fukemy** [comment]
thanks, waiting for it

**Comment by ferhatabd** [comment]
Hi @fukemy, 
I've just updated the framework. It now works without any pods.
You can just clone the repo and try to build it. 
You can also have a look in the [example project](https://github.com/ferhatabd/FAStoryKitStarter) if you need to.
Hope this helps 😊
